version: 0.2

env:
  variables:
    # SOURCE_VERSION: $(echo $CODEBUILD_RESOLVED_SOURCE_VERSION)
    MODEL_DATA: "<your s3 path>"
    ROLE: "<your role>"
    ENTRY_POINT: "cifar10.py"
    SOURCE_DIR: "src"
    FRAMEWORK_VERSION: "1.12.0"
    INITIAL_INSTANCE_COUNT: 1
    INSTANCE_TYPE: "ml.m4.xlarge"

phases:
  install:
    runtime-versions:
      docker: 18
      python: 3.7

  build:
    commands:
      - pip install sagemaker
      - python test_deploy.py  --model_data $MODEL_DATA --role $ROLE --entry_point $ENTRY_POINT --src_dir $SOURCE_DIR --framework_version $FRAMEWORK_VERSION --initial_instance_count $INITIAL_INSTANCE_COUNT --instance_type $INSTANCE_TYPE
